name: mpris_service
version: 1.0.0
description: A Dart library to integrate Media Player Remote Interfacing Specification (MPRIS).
homepage: https://github.com/alexmercerind/mpris_service
repository: https://github.com/alexmercerind/mpris_service
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dbus: ^0.7.1
  path: ^1.8.1
  base_x: ^2.0.0
  collection: ^1.17.0

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.0
