name: mpris_service
homepage: https://github.com/alexmercerind/mpris_service.dart
repository: https://github.com/alexmercerind/mpris_service.dart
description: A Dart library to integrate Media Player Remote Interfacing Specification (MPRIS). Based on dbus.dart package.
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dbus: ^0.7.1
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
